import profileData from '../data/profile.json';
import educationData from '../data/education.json';
import awardsData from '../data/awards.json';
import contactData from '../data/contact.json';
import cvData from '../data/cv.json';
import researchData from '../data/research.json';
import publicationData from '../data/publications.json';
import skillData from '../data/skills.json';
import { normalizeAwards, normalizeProfile, normalizeContact, normalizeCV, normalizeEntries, normalizePublications, normalizeResearch, normalizeSkills } from './normalize';
export type { Media, Publication, Research, Skill, Entry } from './normalize';
export const profile = normalizeProfile(profileData);
export const contact = normalizeContact(contactData);
export const cv = normalizeCV(cvData);
export const education = normalizeEntries(educationData);
export const awards = normalizeAwards(awardsData);
export const publications = normalizePublications(publicationData);
export const research = normalizeResearch(researchData);
export const skills = normalizeSkills(skillData);

export { publicationGroups, isHomePublication } from './normalize';
